name: Update translations in main branch automatically
on:
  push:
    branches:
      - main
    paths-ignore:
      - po/*

jobs:
  update-po:
    name: Update po files
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y gettext
      # Checkout code with git
      - uses: actions/checkout@v3
        with:
          ref: main
      # Install go
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      # Update po if needed
      - name: Check po files
        id: checkpo
        run: |
          set -eu

          hasModif="false"
          go generate ./internal/i18n/
          # Exclude line diffs only
          MODIFIED=$(git difftool -y -x "diff -Nup -I '^#: '" po/)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "modified=${hasModif}" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.modified == 'true' }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Auto update po files
          title: Auto update po files
          labels: po, automated pr
          body: "[Auto-generated pull request](https://github.com/ubuntu/aad-auth/actions/workflows/auto-updates.yaml) by GitHub Action"
          branch: auto-update-po
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push branch
        if: ${{ env.modified == 'true' }}
        run: |
          git push origin auto-update-po:main
