name: QA
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  go:
    name: Go - Code quality and mod files up to date
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y libpam-dev libglib2.0-dev gcc
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Get version of golanci-lint to use
        id: cilint-version-fetch
        # This handles "require foo version" and "require (\nfoo version\n)"" formats
        run: echo "version=$(grep golangci-lint tools/go.mod | rev | cut -f1 -d' ' | rev)" >> $GITHUB_OUTPUT
      - name: Code formatting, vet, static checker Security…
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ steps.cilint-version-fetch.outputs.version }}
          args: "--config .golangci-ci.yaml"
      - name: Module files are up to date
        run: |
          set -eu

          go mod tidy
          MODIFIED=`git status --porcelain go.sum go.mod`
          if [ -n "$MODIFIED" ]; then
              echo "ERROR: go module files aren't up to date:"
              git --no-pager diff go.mod go.sum
              exit 1
          fi
        if: ${{ always() }}
      - name: Building PAM
        run: |
          # Build PAM library
          go build -ldflags='-s -w' -buildmode=c-shared -o pam_aad.so ./pam
        if: ${{ always() }}
  rust:
    name: Rust - Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build crate
        uses: actions-rs/cargo@v1
        with:
          command: build
          args:  --all-features
      - name: Check code format with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Check code format with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
