[package]
name = "nss_aad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[features]
integration_tests = []

[dependencies]
ctor = "0.1.26"
libnss = "0.4.0"
libc = "0.2.71"
log = "0.4.17"
lazy_static = "1.4.0"
paste = "1.0.11"
rusqlite = "0.28.0"
syslog = "6.0.1"
